### ISSUE TITLE
Data Eng Setup - Poetry install gets errors on some folders

### ISSUE THREAD

**Issue by matheussposito** [lewagon/data-engineering-setup#46]
Some students reported that while running the `make install` command the poetry install command reported an error on some folders.

I couldn't track all the folders that this happened, but I reproduced the error on the 00-Test-Setup folder (image below).

The error line is `pyproject.toml changed significantly since poetry.lock was last generated. Run poetry lock [--no-update] to fix the lock file.`

The error prevented the install from happening and the student had to manually fix the poetry lock file and than run the poetry install command again

![image](https://github.com/lewagon/data-engineering-setup/assets/82531850/982658ec-ab68-4f5a-a1f1-3c7ae3e8f10d)

**Comment by lorcanrae** [comment]
The `poetry.lock` files for all challenges need to be redone and tested against solutions for compatibility - it's going to take some time.

Inherently I don't have an issue with some of these messages because it forces students to engage with poetry, which is largely abstracted away from them with `layout_poetry`.
